import type { Party } from '@/lib/types';

export const parties: Party[] = [
  ['Kaitlyn Holt', 'David Sinclair'],
  ['Jane Sinclair', 'Doug Palm'],
  ['Dwight Burke'],
  ['Sharlene McEachern'],
  ['Kathryn Holt', 'Bill Holt', 'Kathleen Holt'],
  ['Jay Holt'],
  ['Jerry Holt', 'Fran Sawyer'],
  ['Jess Sinclair'],
  ['Sheila Jacobs', 'Kimberly Coon'],
  ['Cassie Knowlton'],
  ['Corrine Roby', 'Michael Wetzel'],
  ['Abigail Odam', 'John Odam'],
  ['Sara Green', 'Richard Green'],
  ['Barbara Ohrstrom'],
  ['Pat Sciotti'],
  ['Molly Sinclair', 'Rachel Piper'],
  ['Steve Palm', 'Tanya Palm'],
  ['Julia Sinclair-Palm', 'Carly Boyce'],
  ['Chris Knowlton', 'Tiffany Knowlton', 'Emma Knowlton'],
  ['John Mooney'],
  ['Kylie Martin', 'Travis Martin'],
  ['Liz Landram'],
  ['Lois Knowlton'],
  ['Mike Sciotti', 'Valerie Sciotti'],
  ['Marty Born', 'Ray Born'],
  ['Rusty Holt', 'Kathy Holt'],
  ['Anzi Jacobs'],
  ['Bruce Knowlton', 'Cyndi Knowlton'],
  ['Maryann Mohns', 'Craig Mohns'],
];
